# Generated by Django 3.2.8 on 2021-10-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educat.type'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
